[book]
language = "en"
multilingual = false
src = "src"
title = "Rust for JavaScript Developers"

[output.html]
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]
git-repository-url = "/"
git-repository-icon = "fa-github"
edit-url-template = "/edit/main/{path}"

[output.html.playground]
runnable = false
